// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var socket;
    socket = io.connect("http://localhost:4000");
    return socket.on("message", function(data) {
      alert("message");
      return $("ul").append("<li>" + data + "</li>");
    });
  });

}).call(this);
