// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var input, socket;
    alert("welcome");
    $("p").html("jQuery test passed");
    $("#log").append("<li>to the low-level chat room </li>");
    input = $("#entry");
    socket = io.connect("http://localhost");
    alert("still running");
    socket.on("news", function(data) {
      return $("#log").append("<li>" + data + "</li>");
    });
    return input.keypress(function(event) {
      var message;
      if (event.which !== 13) {
        return;
      }
      message = input.attr("value");
      if (message) {
        return socket.emit("news", message);
      }
    });
  });

}).call(this);
