// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var socket;
    alert("welcome");
    $("p").html("jQuery test passed");
    $("#log").append("<li>low-level chat room </li>");
    socket = io.connect("http://localhost");
    alert("still running");
    return socket.on("news", function(data) {
      return $("#log").append("<li>" + data + "</li>");
    });
  });

}).call(this);
