// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, io, port, server;

  express = require("express");

  app = express.createServer();

  app.use(express["static"](__dirname));

  app.set("views", __dirname + "/views");

  app.set("view engine", "jade");

  app.get("/", function(req, res) {
    return res.render("index");
  });

  port = process.env.PORT || 5000;

  server = app.listen(port);

  io = require("socket.io").listen(server);

  io.sockets.on("connection", function(socket) {
    var username;
    username = null;
    socket.broadcast.emit("news", "someone has joined us");
    socket.emit("news", "please enter your username");
    socket.on("news", function(data) {
      if (!username) {
        username = data;
      }
      return io.sockets.emit("news", "" + username + " : " + data);
    });
    return socket.on("disconnect", function() {
      return io.sockets.emit("news", "someone has left us");
    });
  });

}).call(this);
