// Generated by CoffeeScript 1.3.3
(function() {
  var app, express;

  express = require("express");

  app = express.createServer();

  app.set("views", __dirname + "/views");

  app.set("view engine", "jade");

  app.get("/", function(req, res) {
    return res.render("index");
  });

  app.listen(4000);

}).call(this);
